name: deploy

on:
  push:
    branches: test

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@master
        with:
          key:      ${{ secrets.SSHKEY }} 
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port:     ${{ secrets.PORT }}
          script: |
            mkdir /root /root/env /root/env/${{ github.event.repository.name }}
            cd ~/env/${{ github.event.repository.name }}
            ls