name: deploy

on:
  push:
    branches: test

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@master
        with:
          key:      ${{ secrets.KEY }} 
          host:     ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port:     ${{ secrets.PORT }}
          script: |
          ls